/*
Enter your query here.
*/

SELECT N, 
CASE
WHEN N IN (SELECT P FROM BST) AND P IS NOT NULL THEN "Inner"
WHEN N IN (SELECT P FROM BST) AND P IS NULL THEN "Root"
ELSE "Leaf"
END
FROM BST
ORDER BY N;
